### ISSUE TITLE
Add generic number/text input box

### ISSUE THREAD

**Issue by ortk95** [georgefst/monpad#30]

**Comment by georgefst** [comment]
Made a start in 1ada83e, but:
- [ ] I'd like to provide some control over styling, including font size.
- [x] Text and number inputs fire events on every keypress. We'd prefer to wait for the user to confirm, which would require a separate button for mobile devices. We could even make this configurable. (submit event introduced in ac044dac8e6eae1a9076b2608b53e0b1ee2bcca6 - see #35 for making it more useful)
- [x] Checkboxes always emit "on", so we always get `InputBool _ True`. (fixed in e492745)
- [ ] It would be nice to just call the `inputType` field "type". We can't do that in Haskell or Elm because it's a keyword, but there should be some workaround for JSON and Dhall.
- [ ] We might want [other input types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input), e.g. radio buttons.

**Comment by georgefst** [comment]
> Checkboxes always emit "on", so we always get `InputBool _ True`

It's actually worse. They seem to always echo the last event. So if, say, we update a layout so that a number input changes to a checkbox, then the checkbox starts emitting numbers (which we fail to decode to `Bool`s, so we don't send an update).

**Comment by georgefst** [comment]
> It would be nice to just call the `inputType` field "type". We can't do that in Haskell or Elm because it's a keyword, but there should be some workaround for JSON and Dhall.

There may be no nice way to do this. We can use `_type` and add `FieldLabelModifier (StripPrefix "_")` to `Opts.JSON` (and a similar option is available for Dhall), but `_type` is not a valid record name in Elm. I can't even find a spec of exactly what names are valid.

**Comment by georgefst** [comment]
Ok. I don't care about the last two, and I've opened #37 to track the first (though we did make the text stylable in 6c6d2220b0399406f68ea25eb941f91b5a3ee954).
