### ISSUE TITLE
Allow the URL to be customised

### ISSUE THREAD

**Issue by ortk95** [georgefst/monpad#42]
It would be useful if the controller URL could be customised so it doesn't have to always be `.../monpad`

**Comment by georgefst** [comment]
This is a reasonable thing to request. Unfortunately the server library I'm using very much assumes that routes are static. But it _can_ be worked around: https://github.com/haskell-servant/servant/issues/634#issuecomment-271146431.

OTOH, there's really not much reason to have a prefix at all. i.e. we could just strip the `/monpad` out of the URL entirely. We'd have to add a prefix for the websocket connection but that seems preferable since the user never sees it.

**Comment by georgefst** [comment]
> OTOH, there's really not much reason to have a prefix at all. i.e. we could just strip the `/monpad` out of the URL entirely. We'd have to add a prefix for the websocket connection but that seems preferable since the user never sees it.

https://github.com/georgefst/monpad/tree/unprefix

**Comment by georgefst** [comment]
I don't think there's any particularly good reason why I put everything behind a "monpad" route. My knowledge of web programming when this project started two years ago was very weak. I think maybe I thought multiple services could easily be run on the same port if the URLs didn't overlap.

**Comment by georgefst** [comment]
> OTOH, there's really not much reason to have a prefix at all

Removed in https://github.com/georgefst/monpad/commit/db6ecc2486b61861afbc5045cb0a453a2cdaa5a6
